/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: public/src/runtime/odyssey/sppe/core/main.C $                 */
/*                                                                        */
/* OpenPOWER sbe Project                                                  */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2019,2023                        */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

#include "sbetrace.H"
#include "globals.H"
#include "sbeexeintf.H"
#include "sberegaccess.H"
#include "sbestates.H"
#include "sbeglobals.H"
#include "ppe42_scom.h"
#include "odysseylink.H"
#include "plat_hw_access.H"
#include "initthreads.H"
#include "target.H"
#include "fapi2_attribute_service.H"
#include "errorcodes.H"
#include "sbeutil.H"
#include "sbe_build_info.H"
#include "ppe42_string.h"
#include "metadata.H"
#include "sbestatesutils.H"
#include "heap.H"
#include "imgcustomize.H"
#include "sbethermalsensorpolltimer.H"
#include "sbetspolling.H"

extern "C" {
#include "pk_api.h"
}
////////////////////////////////////////////////////////////////
//// @brief Stacks for Non-critical Interrupts ( timebase, timers )
////////////////////////////////////////////////////////////////
#define INITIAL_PK_TIMEBASE   0
#define SPPE_NONCRITICAL_STACK_SIZE 512

// SBE Frequency to be used to initialise PK
uint32_t g_odysseyfrequency = SBE_REF_BASE_FREQ_HZ;

uint8_t sppe_Kernel_NC_Int_stack[SPPE_NONCRITICAL_STACK_SIZE];

uint32_t g_partitionOffset = 0;
uint32_t g_partitionSize = 0;

// ody draminit offset address
uint32_t g_draminitOffset = 0;

///////////////////////////////////////////////////////////////////
//// @brief PkThread structure for SBE Verification thread .
////////////////////////////////////////////////////////////////////

extern "C"
{
// These variables are declared in linker script to keep track of
// global constructor pointer functions and bss sections.
extern void (*ctor_start_address)() __attribute__ ((section (".rodata")));
extern void (*ctor_end_address)() __attribute__ ((section (".rodata")));
extern uint64_t _sbss_start __attribute__ ((section (".bss")));
extern uint64_t _bss_end __attribute__ ((section (".bss")));
// This function will be used to do any C++ handling required before doing
// any main job. Call to this function should get generated by
// compiler.
// TODO via RTC 152070
// We are also initialising sbss section to zero this function.
// Though it does not do any harm as of now, it is better  if we use loader
// or linker script to zero init sbss section. This way we will be future
// garded if pk  boot uses some static/global data  initialised to
// false in future.

void __eabi()
{
    do
    {
        // Initialise bss and sbss section.
        uint64_t *startAddr = &_sbss_start;
        while (startAddr != &_bss_end)
        {
            *startAddr = 0;
            startAddr++;
        }
        // Call global constructors
        void(**ctors)() = &ctor_start_address;
        while(ctors != &ctor_end_address)
        {
            (*ctors)();
            ctors++;
        }
    } while (false);
}

} // end extern "C"

// Invoke all metadata for an image inside a constant struct to keep the
// values together.
constexpr struct PACKED metadata_t {
    METADATA(IMG, { IMAGES::RUNTIME });
    METADATA_STR(IID, "odyssey/sppe");
    METADATA(GIT, { SBE_COMMIT_ID });
    METADATA(DAT, { SBE_BUILD_TIME });
    METADATA(TRA, { SPPE_TRACE_START_OFFSET, SPPE_PK_TRACE_SIZE_WITH_HEADER });
    METADATA(HEA, { (uint32_t)&_heap_space_start_, (uint32_t)&_heap_space_size_});
    METADATA(ATR, { (uint32_t)&_attrs_start_, (uint32_t)&_attrs_size_ });
    ImageMetadataHeader end = {0, 0};
} g_image_metadata __attribute__ ((section (".sppe_metadata")));

uint32_t g_metadata_ptr SECTION(".g_metadata_ptr");

////////////////////////////////////////////////////////////////
// @brief - main : ODYSSEY SPPE Application main
////////////////////////////////////////////////////////////////
int  main(int argc, char **argv)
{
    int rc = 0;
    uint64_t loadValue;
    SBE::updateProgressCode(CODE_REACHED_RUNTIME);

    // Update metadata
    g_metadata_ptr = (uint32_t)&g_image_metadata;

    do
    {
        SBE::setSbeGlobalFreqFromScratchOrLFR(CALLER_RUNTIME);

        rc = pk_initialize((PkAddress)sppe_Kernel_NC_Int_stack,
                SPPE_NONCRITICAL_STACK_SIZE,
                INITIAL_PK_TIMEBASE, // initial_timebase
                CMN_GLOBAL->sbefreq,
                SPPE_TRACE_START_OFFSET,
                SPPE_PK_TRACE_SIZE);
        if (rc)
        {
            SBE::updateErrorCodeAndHalt(BOOT_RC_SPPE_PK_INIT_FAILED);
        }
        // printing the freq value here, since from here onward tracing is supported
        SBE_INFO(SBE_FUNC "Completed PK initialization for SPPE Image with freq: %d",
                            CMN_GLOBAL->sbefreq);

        sbeSecurityCheckWrap();

        // Initialize SBE Globals instance.
        sbeGlobal = &SBEGlobalsSingleton::getInstance();

        const uint32_t i_target = 0;
        rc = fapi2::getscom_abs_wrap(&i_target, 0x50009, &loadValue);
        SBE_INFO("SBE Messaging Register : 0x%08X 0x%08X",
                (loadValue >> 32) & 0xFFFFFFFF, (loadValue & 0xFFFFFFFF));

        // Initialize the semaphores.
        rc = sbeInitSems();
        if (rc)
        {
            break;
        }
        // Initialize SBE control loop threads
        rc = sbeInitThreads();
        if (rc)
        {
            break;
        }
        // Setup SBE PPE IRQs
        rc = sbeIRQSetup();
        if (rc)
        {
            break;
        }

        // Initialize heap space after bootloader has loaded paks to pibmem
        Heap::get_instance().initialize();

        fapi2::ReturnCode fapiRc = g_platTarget->plat_targetsInit();
        if( fapiRc != fapi2::FAPI2_RC_SUCCESS )
        {
            SBE_ERROR(SBE_FUNC"plat_targetsInit failed  fapiRc 0x%08x",fapiRc);
            stateTransition(SBE_EVENT_CMN_FAILURE);
            // Hard Reset SBE to recover
            break;
        }

        plat_AttrInit(fapi2::ENUM_ATTR_NAME_ODYSSEY);

        if(SbeRegAccess::theSbeRegAccess().init())
        {
            SBE_ERROR(SBE_FUNC"Failed to initialize SbeRegAccess.");
            // init failure could mean the below will fail too, but attempt it
            // anyway
            stateTransition(SBE_EVENT_CMN_FAILURE);
            // Hard Reset SBE to recover
            break;
        }

        sbePakSearchStartOffset();

        // Start the timer for the async thread.
        rc = g_sbe_thermal_sensor_timer.startTimer(
                             THERMAL_SENSOR_POLLING_INITIAL_PERIOD_MICROSEC,
                             (PkTimerCallback)&sbeasyncthreadPkExpiryCallback );
        if(rc)
        {
            SBE_ERROR(SBE_FUNC "Failed to start the async thread timer with rc"
                               " 0x%08X", rc);
            break;
        }

        SBE_INFO(SBE_FUNC "Start all the threads.");
        // Start running the highest priority thread.
        // This function never returns
        pk_start_threads();

    }while(false);

    // Halt if exited from the loop incase of error
    pk_halt();

    SBE_EXIT(SBE_FUNC);
    return 0;
}
