/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: public/src/runtime/odyssey/sppe/core/main.C $                 */
/*                                                                        */
/* OpenPOWER sbe Project                                                  */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2019,2022                        */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

#include "trace.H"
#include "globals.H"
#include "sbeexeintf.H"

extern "C" {
#include "pk_api.h"
}

////////////////////////////////////////////////////////////////
//// @brief Stacks for Non-critical Interrupts ( timebase, timers )
////////////////////////////////////////////////////////////////
#define INITIAL_PK_TIMEBASE   0
#define SPPE_NONCRITICAL_STACK_SIZE 512

// SBE Frequency to be used to initialise PK
uint32_t g_odysseyfreqency = SBE_REF_BASE_FREQ_HZ;

uint8_t sppe_Kernel_NC_Int_stack[SPPE_NONCRITICAL_STACK_SIZE];

///////////////////////////////////////////////////////////////////
//// @brief PkThread structure for SBE Verification thread .
////////////////////////////////////////////////////////////////////

extern "C"
{
// These variables are declared in linker script to keep track of
// global constructor pointer functions and sbss section.
extern void (*ctor_start_address)() __attribute__ ((section (".rodata")));
extern void (*ctor_end_address)() __attribute__ ((section (".rodata")));
extern uint64_t _sbss_start __attribute__ ((section (".sbss")));
extern uint64_t _sbss_end __attribute__ ((section (".sbss")));
// This function will be used to do any C++ handling required before doing
// any main job. Call to this function should get generated by
// compiler.
// TODO via RTC 152070
// We are also initialising sbss section to zero this function.
// Though it does not do any harm as of now, it is better  if we use loader
// or linker script to zero init sbss section. This way we will be future
// garded if pk  boot uses some static/global data  initialised to
// false in future.

void __eabi()
{
    do
    {
        // Initialise sbss section
        uint64_t *startAddr = &_sbss_start;
        while ( startAddr != &_sbss_end )
        {
            *startAddr = 0;
            startAddr++;
        }
        // Call global constructors
        void(**ctors)() = &ctor_start_address;
        while( ctors != &ctor_end_address)
        {
            (*ctors)();
            ctors++;
        }
    } while (false);
}

} // end extern "C"

////////////////////////////////////////////////////////////////
// @brief - main : ODYSSEY SPPE Application main
////////////////////////////////////////////////////////////////
int  main(int argc, char **argv)
{
    #define OSPPE_FUNC " OSPPE_main "

    int rc = 0;

    do
    {
        rc = pk_initialize((PkAddress)sppe_Kernel_NC_Int_stack,
                SPPE_NONCRITICAL_STACK_SIZE,
                INITIAL_PK_TIMEBASE, // initial_timebase
                g_odysseyfreqency );

        OSPPE_ENTER(OSPPE_FUNC);

        if (rc)
        {
            OSPPE_ERROR(OSPPE_FUNC "PK Initialization failed for SPPE image");
            break;
        }
        OSPPE_INFO(OSPPE_FUNC "Completed PK initialization for SPPE Image");

    }while(true);

    OSPPE_EXIT(OSPPE_FUNC);
    return 0;
}
