/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: public/src/runtime/odyssey/sppe/core/main.C $                 */
/*                                                                        */
/* OpenPOWER sbe Project                                                  */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2019,2022                        */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

#include "sbetrace.H"
#include "globals.H"
#include "sbeexeintf.H"
#include "sberegaccess.H"
#include "sbestates.H"
#include "sbeglobals.H"
#include "ppe42_scom.h"
#include "odysseylink.H"
#include "plat_hw_access.H"
#include "initthreads.H"
#include "target.H"

extern "C" {
#include "pk_api.h"
}

////////////////////////////////////////////////////////////////
//// @brief Stacks for Non-critical Interrupts ( timebase, timers )
////////////////////////////////////////////////////////////////
#define INITIAL_PK_TIMEBASE   0
#define SPPE_NONCRITICAL_STACK_SIZE 512

// SBE Frequency to be used to initialise PK
uint32_t g_odysseyfreqency = SBE_REF_BASE_FREQ_HZ;

uint8_t sppe_Kernel_NC_Int_stack[SPPE_NONCRITICAL_STACK_SIZE];

///////////////////////////////////////////////////////////////////
//// @brief PkThread structure for SBE Verification thread .
////////////////////////////////////////////////////////////////////

extern "C"
{
// These variables are declared in linker script to keep track of
// global constructor pointer functions and bss sections.
extern void (*ctor_start_address)() __attribute__ ((section (".rodata")));
extern void (*ctor_end_address)() __attribute__ ((section (".rodata")));
extern uint64_t _sbss_start __attribute__ ((section (".bss")));
extern uint64_t _bss_end __attribute__ ((section (".bss")));
// This function will be used to do any C++ handling required before doing
// any main job. Call to this function should get generated by
// compiler.
// TODO via RTC 152070
// We are also initialising sbss section to zero this function.
// Though it does not do any harm as of now, it is better  if we use loader
// or linker script to zero init sbss section. This way we will be future
// garded if pk  boot uses some static/global data  initialised to
// false in future.

void __eabi()
{
    do
    {
        // Initialise bss and sbss section.
        uint64_t *startAddr = &_sbss_start;
        while (startAddr != &_bss_end)
        {
            *startAddr = 0;
            startAddr++;
        }
        // Call global constructors
        void(**ctors)() = &ctor_start_address;
        while(ctors != &ctor_end_address)
        {
            (*ctors)();
            ctors++;
        }
    } while (false);
}

} // end extern "C"

////////////////////////////////////////////////////////////////
// @brief - main : ODYSSEY SPPE Application main
////////////////////////////////////////////////////////////////
int  main(int argc, char **argv)
{
    #define SBE_FUNC " OSPPE_main "
    SBE_ENTER(SBE_FUNC);

    // Initialize SBEGlobals instance.
    sbeGlobal = &SBEGlobalsSingleton::getInstance();

    uint64_t loadValue = (uint64_t)(SBE_CODE_BOOT_PIBMEM_MAIN_MSG)<<32;
    PPE_STVD(0x50009, loadValue);
    int rc = 0;

    const uint32_t i_target = 0;
    rc = fapi2::getscom_abs_wrap(&i_target, 0x50009, &loadValue);
    SBE_ERROR("0x%08X 0x%08X", (loadValue >> 32) & 0xFFFFFFFF, (loadValue & 0xFFFFFFFF));

    do
    {
        rc = pk_initialize((PkAddress)sppe_Kernel_NC_Int_stack,
                SPPE_NONCRITICAL_STACK_SIZE,
                INITIAL_PK_TIMEBASE, // initial_timebase
                g_odysseyfreqency );

        if (rc)
        {
            SBE_ERROR(SBE_FUNC "PK Initialization failed for SPPE image");
            break;
        }
        SBE_INFO(SBE_FUNC "Completed PK initialization for SPPE Image");

        // Initialize the semaphores.
        rc = sbeInitSems();
        if (rc)
        {
            break;
        }
        // Initialize SBE control loop threads
        rc = sbeInitThreads();
        if (rc)
        {
            break;
        }
        // Setup SBE PPE IRQs
        rc = sbeIRQSetup();
        if (rc)
        {
            break;
        }

        //if ( (!SBE::isMpiplReset()) && (!SBE_GLOBAL->isHreset) )
        {
            fapi2::ReturnCode fapiRc = g_platTarget->plat_TargetsInit();
            if( fapiRc != fapi2::FAPI2_RC_SUCCESS )
            {
                SBE_ERROR(SBE_FUNC"plat_TargetsInit failed");
                (void)SbeRegAccess::theSbeRegAccess().
                        stateTransition(SBE_FAILURE_EVENT);
                // Hard Reset SBE to recover
                break;
            }

            if(SbeRegAccess::theSbeRegAccess().init())
            {
                SBE_ERROR(SBE_FUNC"Failed to initialize SbeRegAccess.");
                // init failure could mean the below will fail too, but attempt it
                // anyway
                (void)SbeRegAccess::theSbeRegAccess().stateTransition(
                                                     SBE_FAILURE_EVENT);
                // Hard Reset SBE to recover
                break;
            }
        }
        // Start running the highest priority thread.
        // This function never returns
        pk_start_threads();

    }while(false);

    while(1);

    SBE_EXIT(SBE_FUNC);
    return 0;
}
