/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: public/src/onetime/odyssey/bldr/core/main.C $                 */
/*                                                                        */
/* OpenPOWER sbe Project                                                  */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2019,2022                        */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

#include "sbetrace.H"
#include "threadroutine.H"
#include "globals.H"
#include "sbeexeintf.H"
#include "threadutil.H"
#include "mbxscratch.H"
#include "ppe42_scom.h"
#include "progresscode.H"
#include "sbeutil.H"

extern "C" {
#include "pk_api.h"
}

// SBE Frequency to be used to initialise PK
uint32_t g_odysseyfreqency = SBE_REF_BASE_FREQ_HZ;

uint8_t bldr_Kernel_NC_Int_stack[BLDR_NONCRITICAL_STACK_SIZE];
uint8_t bldrSecureBoot_stack[BLDR_THREAD_SECURE_BOOT_STACK_SIZE];

///////////////////////////////////////////////////////////////////
//// @brief PkThread structure for ODYSSEY Boot Loader thread .
////////////////////////////////////////////////////////////////////
PkThread bldr_thread;

extern "C"
{
// These variables are declared in linker script to keep track of
// global constructor pointer functions and bss sections.
extern void (*ctor_start_address)() __attribute__ ((section (".rodata")));
extern void (*ctor_end_address)() __attribute__ ((section (".rodata")));
extern uint64_t _sbss_start __attribute__ ((section (".bss")));
extern uint64_t _bss_end __attribute__ ((section (".bss")));
// This function will be used to do any C++ handling required before doing
// any main job. Call to this function should get generated by
// compiler.
// TODO via RTC 152070
// We are also initialising sbss section to zero this function.
// Though it does not do any harm as of now, it is better  if we use loader
// or linker script to zero init sbss section. This way we will be future
// garded if pk  boot uses some static/global data  initialised to
// false in future.

void __eabi()
{
    UPDATE_BLDR_SBE_PROGRESS_CODE(EABI_ENTER);

    do
    {
        // Initialise bss and sbss section.
        uint64_t *startAddr = &_sbss_start;
        while (startAddr != &_bss_end)
        {
            *startAddr = 0;
            startAddr++;
        }
        // Call global constructors
        void(**ctors)() = &ctor_start_address;
        while(ctors != &ctor_end_address)
        {
            (*ctors)();
            ctors++;
        }
    } while (false);

     UPDATE_BLDR_SBE_PROGRESS_CODE(EABI_EXIT);
}

} // end extern "C"

////////////////////////////////////////////////////////////////
// @brief - main : ODYSSEY Boot Loader Application main
////////////////////////////////////////////////////////////////
int  main(int argc, char **argv)
{
    #define SBE_FUNC " Boot Loader SBE_main "

    int rc = 0;

    do
    {
        //Clear out old progress code
        UPDATE_BLDR_SBE_PROGRESS_CODE(0x00)
        UPDATE_BLDR_SBE_PROGRESS_CODE(ENTERED_BLDR_MAIN);

        rc = pk_initialize((PkAddress)bldr_Kernel_NC_Int_stack,
                BLDR_NONCRITICAL_STACK_SIZE,
                INITIAL_PK_TIMEBASE, // initial_timebase
                g_odysseyfreqency );

        SBE_ENTER(SBE_FUNC);

        UPDATE_BLDR_SBE_PROGRESS_CODE(COMPLETED_PK_INIT)

        if (rc)
        {
            SBE_ERROR(SBE_FUNC "PK Initialization failed for Boot Loader image");
            break;
        }
        SBE_INFO(SBE_FUNC "Completed PK initialization for Boot Loader Image");

        //Initialize Boot Loader Thread
        rc = createAndResumeThreadHelper(&bldr_thread,
                 bldrthreadroutine,
                (void *)0,
                (PkAddress)bldrSecureBoot_stack,
                BLDR_THREAD_SECURE_BOOT_STACK_SIZE,
                THREAD_PRIORITY_5);
        if (rc)
        {
            SBE_ERROR(SBE_FUNC "Initialize Boot Loader secure boot thread failed with rc 0x%08X", rc);
            break;
        }

        SBE_INFO(SBE_FUNC "bldrSecureBoot_thread thread initilised");

        UPDATE_BLDR_SBE_PROGRESS_CODE(COMPLETED_THREAD_CREATION)

        pk_start_threads();

    }while(false);

    SBE_EXIT(SBE_FUNC);
    return 0;
}
